# Source: rms-api-app/templates/autoscale.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  labels:
    app: guestbook
    tier: frontned
spec:
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 75

  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: frontend